version: "3.9"
services:
  synapse:
    container_name: synapse
    image: matrixdotorg/synapse
    volumes:
      - ./synapse/data:/data
    ports:
      - 8008:8008
    environment:
        SYNAPSE_SERVER_NAME: "matrix.matsu.fi"
        SYNAPSE_REPORT_STATS: "yes"

  registration:
    container_name: registration
    image: matrix-registration
    ports:
      - 5000:5000
    volumes:
      - ./matrix-registration/data:/data
    command: ["serve"]
